/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Artwork {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'image' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export interface TextContent {
  'bio' : string,
  'tagline' : string,
  'artistName' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addArtwork' : ActorMethod<[string, string, ExternalBlob], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteArtwork' : ActorMethod<[bigint], undefined>,
  'getAllArtworks' : ActorMethod<[], Array<Artwork>>,
  'getArtistPortrait' : ActorMethod<[], [] | [ExternalBlob]>,
  'getArtwork' : ActorMethod<[bigint], [] | [Artwork]>,
  'getArtworksByDescription' : ActorMethod<[string], Array<Artwork>>,
  'getArtworksByTitle' : ActorMethod<[string], Array<Artwork>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoverImage' : ActorMethod<[], [] | [ExternalBlob]>,
  'getLogo' : ActorMethod<[], [] | [ExternalBlob]>,
  'getTextContent' : ActorMethod<[], TextContent>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateArtwork' : ActorMethod<
    [bigint, string, string, ExternalBlob],
    undefined
  >,
  'updateTextContent' : ActorMethod<[string, string, string], undefined>,
  'uploadArtistPortrait' : ActorMethod<[ExternalBlob], undefined>,
  'uploadCoverImage' : ActorMethod<[ExternalBlob], undefined>,
  'uploadLogo' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];